/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example.flink.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Customer extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 2277883453817313222L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Customer\",\"namespace\":\"com.example.flink.avro\",\"fields\":[{\"name\":\"id\",\"type\":\"long\"},{\"name\":\"username\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"password\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"fname\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"lname\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"bday\",\"type\":[\"null\",{\"type\":\"int\",\"logicalType\":\"date\"}],\"default\":null},{\"name\":\"address\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"email\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"phone\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"create_at\",\"type\":[\"null\",{\"type\":\"long\",\"logicalType\":\"timestamp-micros\"}],\"default\":null},{\"name\":\"update_at\",\"type\":[\"null\",{\"type\":\"long\",\"logicalType\":\"timestamp-micros\"}],\"default\":null},{\"name\":\"status\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"role\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.DateConversion());
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMicrosConversion());
  }

  private static final BinaryMessageEncoder<Customer> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Customer> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Customer> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Customer> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Customer> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Customer to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Customer from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Customer instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Customer fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private long id;
  private java.lang.String username;
  private java.lang.String password;
  private java.lang.String fname;
  private java.lang.String lname;
  private java.time.LocalDate bday;
  private java.lang.String address;
  private java.lang.String email;
  private java.lang.String phone;
  private java.time.Instant create_at;
  private java.time.Instant update_at;
  private java.lang.String status;
  private java.lang.String role;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Customer() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param username The new value for username
   * @param password The new value for password
   * @param fname The new value for fname
   * @param lname The new value for lname
   * @param bday The new value for bday
   * @param address The new value for address
   * @param email The new value for email
   * @param phone The new value for phone
   * @param create_at The new value for create_at
   * @param update_at The new value for update_at
   * @param status The new value for status
   * @param role The new value for role
   */
  public Customer(java.lang.Long id, java.lang.String username, java.lang.String password, java.lang.String fname, java.lang.String lname, java.time.LocalDate bday, java.lang.String address, java.lang.String email, java.lang.String phone, java.time.Instant create_at, java.time.Instant update_at, java.lang.String status, java.lang.String role) {
    this.id = id;
    this.username = username;
    this.password = password;
    this.fname = fname;
    this.lname = lname;
    this.bday = bday;
    this.address = address;
    this.email = email;
    this.phone = phone;
    this.create_at = create_at;
    this.update_at = update_at;
    this.status = status;
    this.role = role;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return username;
    case 2: return password;
    case 3: return fname;
    case 4: return lname;
    case 5: return bday;
    case 6: return address;
    case 7: return email;
    case 8: return phone;
    case 9: return create_at;
    case 10: return update_at;
    case 11: return status;
    case 12: return role;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Long)value$; break;
    case 1: username = value$ != null ? value$.toString() : null; break;
    case 2: password = value$ != null ? value$.toString() : null; break;
    case 3: fname = value$ != null ? value$.toString() : null; break;
    case 4: lname = value$ != null ? value$.toString() : null; break;
    case 5: bday = (java.time.LocalDate)value$; break;
    case 6: address = value$ != null ? value$.toString() : null; break;
    case 7: email = value$ != null ? value$.toString() : null; break;
    case 8: phone = value$ != null ? value$.toString() : null; break;
    case 9: create_at = (java.time.Instant)value$; break;
    case 10: update_at = (java.time.Instant)value$; break;
    case 11: status = value$ != null ? value$.toString() : null; break;
    case 12: role = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public long getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(long value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'username' field.
   * @return The value of the 'username' field.
   */
  public java.lang.String getUsername() {
    return username;
  }


  /**
   * Sets the value of the 'username' field.
   * @param value the value to set.
   */
  public void setUsername(java.lang.String value) {
    this.username = value;
  }

  /**
   * Gets the value of the 'password' field.
   * @return The value of the 'password' field.
   */
  public java.lang.String getPassword() {
    return password;
  }


  /**
   * Sets the value of the 'password' field.
   * @param value the value to set.
   */
  public void setPassword(java.lang.String value) {
    this.password = value;
  }

  /**
   * Gets the value of the 'fname' field.
   * @return The value of the 'fname' field.
   */
  public java.lang.String getFname() {
    return fname;
  }


  /**
   * Sets the value of the 'fname' field.
   * @param value the value to set.
   */
  public void setFname(java.lang.String value) {
    this.fname = value;
  }

  /**
   * Gets the value of the 'lname' field.
   * @return The value of the 'lname' field.
   */
  public java.lang.String getLname() {
    return lname;
  }


  /**
   * Sets the value of the 'lname' field.
   * @param value the value to set.
   */
  public void setLname(java.lang.String value) {
    this.lname = value;
  }

  /**
   * Gets the value of the 'bday' field.
   * @return The value of the 'bday' field.
   */
  public java.time.LocalDate getBday() {
    return bday;
  }


  /**
   * Sets the value of the 'bday' field.
   * @param value the value to set.
   */
  public void setBday(java.time.LocalDate value) {
    this.bday = value;
  }

  /**
   * Gets the value of the 'address' field.
   * @return The value of the 'address' field.
   */
  public java.lang.String getAddress() {
    return address;
  }


  /**
   * Sets the value of the 'address' field.
   * @param value the value to set.
   */
  public void setAddress(java.lang.String value) {
    this.address = value;
  }

  /**
   * Gets the value of the 'email' field.
   * @return The value of the 'email' field.
   */
  public java.lang.String getEmail() {
    return email;
  }


  /**
   * Sets the value of the 'email' field.
   * @param value the value to set.
   */
  public void setEmail(java.lang.String value) {
    this.email = value;
  }

  /**
   * Gets the value of the 'phone' field.
   * @return The value of the 'phone' field.
   */
  public java.lang.String getPhone() {
    return phone;
  }


  /**
   * Sets the value of the 'phone' field.
   * @param value the value to set.
   */
  public void setPhone(java.lang.String value) {
    this.phone = value;
  }

  /**
   * Gets the value of the 'create_at' field.
   * @return The value of the 'create_at' field.
   */
  public java.time.Instant getCreateAt() {
    return create_at;
  }


  /**
   * Sets the value of the 'create_at' field.
   * @param value the value to set.
   */
  public void setCreateAt(java.time.Instant value) {
    this.create_at = value;
  }

  /**
   * Gets the value of the 'update_at' field.
   * @return The value of the 'update_at' field.
   */
  public java.time.Instant getUpdateAt() {
    return update_at;
  }


  /**
   * Sets the value of the 'update_at' field.
   * @param value the value to set.
   */
  public void setUpdateAt(java.time.Instant value) {
    this.update_at = value;
  }

  /**
   * Gets the value of the 'status' field.
   * @return The value of the 'status' field.
   */
  public java.lang.String getStatus() {
    return status;
  }


  /**
   * Sets the value of the 'status' field.
   * @param value the value to set.
   */
  public void setStatus(java.lang.String value) {
    this.status = value;
  }

  /**
   * Gets the value of the 'role' field.
   * @return The value of the 'role' field.
   */
  public java.lang.String getRole() {
    return role;
  }


  /**
   * Sets the value of the 'role' field.
   * @param value the value to set.
   */
  public void setRole(java.lang.String value) {
    this.role = value;
  }

  /**
   * Creates a new Customer RecordBuilder.
   * @return A new Customer RecordBuilder
   */
  public static com.example.flink.avro.Customer.Builder newBuilder() {
    return new com.example.flink.avro.Customer.Builder();
  }

  /**
   * Creates a new Customer RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Customer RecordBuilder
   */
  public static com.example.flink.avro.Customer.Builder newBuilder(com.example.flink.avro.Customer.Builder other) {
    if (other == null) {
      return new com.example.flink.avro.Customer.Builder();
    } else {
      return new com.example.flink.avro.Customer.Builder(other);
    }
  }

  /**
   * Creates a new Customer RecordBuilder by copying an existing Customer instance.
   * @param other The existing instance to copy.
   * @return A new Customer RecordBuilder
   */
  public static com.example.flink.avro.Customer.Builder newBuilder(com.example.flink.avro.Customer other) {
    if (other == null) {
      return new com.example.flink.avro.Customer.Builder();
    } else {
      return new com.example.flink.avro.Customer.Builder(other);
    }
  }

  /**
   * RecordBuilder for Customer instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Customer>
    implements org.apache.avro.data.RecordBuilder<Customer> {

    private long id;
    private java.lang.String username;
    private java.lang.String password;
    private java.lang.String fname;
    private java.lang.String lname;
    private java.time.LocalDate bday;
    private java.lang.String address;
    private java.lang.String email;
    private java.lang.String phone;
    private java.time.Instant create_at;
    private java.time.Instant update_at;
    private java.lang.String status;
    private java.lang.String role;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.example.flink.avro.Customer.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.username)) {
        this.username = data().deepCopy(fields()[1].schema(), other.username);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.password)) {
        this.password = data().deepCopy(fields()[2].schema(), other.password);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.fname)) {
        this.fname = data().deepCopy(fields()[3].schema(), other.fname);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.lname)) {
        this.lname = data().deepCopy(fields()[4].schema(), other.lname);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.bday)) {
        this.bday = data().deepCopy(fields()[5].schema(), other.bday);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.address)) {
        this.address = data().deepCopy(fields()[6].schema(), other.address);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.email)) {
        this.email = data().deepCopy(fields()[7].schema(), other.email);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.phone)) {
        this.phone = data().deepCopy(fields()[8].schema(), other.phone);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
      if (isValidValue(fields()[9], other.create_at)) {
        this.create_at = data().deepCopy(fields()[9].schema(), other.create_at);
        fieldSetFlags()[9] = other.fieldSetFlags()[9];
      }
      if (isValidValue(fields()[10], other.update_at)) {
        this.update_at = data().deepCopy(fields()[10].schema(), other.update_at);
        fieldSetFlags()[10] = other.fieldSetFlags()[10];
      }
      if (isValidValue(fields()[11], other.status)) {
        this.status = data().deepCopy(fields()[11].schema(), other.status);
        fieldSetFlags()[11] = other.fieldSetFlags()[11];
      }
      if (isValidValue(fields()[12], other.role)) {
        this.role = data().deepCopy(fields()[12].schema(), other.role);
        fieldSetFlags()[12] = other.fieldSetFlags()[12];
      }
    }

    /**
     * Creates a Builder by copying an existing Customer instance
     * @param other The existing instance to copy.
     */
    private Builder(com.example.flink.avro.Customer other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.username)) {
        this.username = data().deepCopy(fields()[1].schema(), other.username);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.password)) {
        this.password = data().deepCopy(fields()[2].schema(), other.password);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.fname)) {
        this.fname = data().deepCopy(fields()[3].schema(), other.fname);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.lname)) {
        this.lname = data().deepCopy(fields()[4].schema(), other.lname);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.bday)) {
        this.bday = data().deepCopy(fields()[5].schema(), other.bday);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.address)) {
        this.address = data().deepCopy(fields()[6].schema(), other.address);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.email)) {
        this.email = data().deepCopy(fields()[7].schema(), other.email);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.phone)) {
        this.phone = data().deepCopy(fields()[8].schema(), other.phone);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.create_at)) {
        this.create_at = data().deepCopy(fields()[9].schema(), other.create_at);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.update_at)) {
        this.update_at = data().deepCopy(fields()[10].schema(), other.update_at);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.status)) {
        this.status = data().deepCopy(fields()[11].schema(), other.status);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.role)) {
        this.role = data().deepCopy(fields()[12].schema(), other.role);
        fieldSetFlags()[12] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public long getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.example.flink.avro.Customer.Builder setId(long value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.example.flink.avro.Customer.Builder clearId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'username' field.
      * @return The value.
      */
    public java.lang.String getUsername() {
      return username;
    }


    /**
      * Sets the value of the 'username' field.
      * @param value The value of 'username'.
      * @return This builder.
      */
    public com.example.flink.avro.Customer.Builder setUsername(java.lang.String value) {
      validate(fields()[1], value);
      this.username = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'username' field has been set.
      * @return True if the 'username' field has been set, false otherwise.
      */
    public boolean hasUsername() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'username' field.
      * @return This builder.
      */
    public com.example.flink.avro.Customer.Builder clearUsername() {
      username = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'password' field.
      * @return The value.
      */
    public java.lang.String getPassword() {
      return password;
    }


    /**
      * Sets the value of the 'password' field.
      * @param value The value of 'password'.
      * @return This builder.
      */
    public com.example.flink.avro.Customer.Builder setPassword(java.lang.String value) {
      validate(fields()[2], value);
      this.password = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'password' field has been set.
      * @return True if the 'password' field has been set, false otherwise.
      */
    public boolean hasPassword() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'password' field.
      * @return This builder.
      */
    public com.example.flink.avro.Customer.Builder clearPassword() {
      password = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'fname' field.
      * @return The value.
      */
    public java.lang.String getFname() {
      return fname;
    }


    /**
      * Sets the value of the 'fname' field.
      * @param value The value of 'fname'.
      * @return This builder.
      */
    public com.example.flink.avro.Customer.Builder setFname(java.lang.String value) {
      validate(fields()[3], value);
      this.fname = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'fname' field has been set.
      * @return True if the 'fname' field has been set, false otherwise.
      */
    public boolean hasFname() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'fname' field.
      * @return This builder.
      */
    public com.example.flink.avro.Customer.Builder clearFname() {
      fname = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'lname' field.
      * @return The value.
      */
    public java.lang.String getLname() {
      return lname;
    }


    /**
      * Sets the value of the 'lname' field.
      * @param value The value of 'lname'.
      * @return This builder.
      */
    public com.example.flink.avro.Customer.Builder setLname(java.lang.String value) {
      validate(fields()[4], value);
      this.lname = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'lname' field has been set.
      * @return True if the 'lname' field has been set, false otherwise.
      */
    public boolean hasLname() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'lname' field.
      * @return This builder.
      */
    public com.example.flink.avro.Customer.Builder clearLname() {
      lname = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'bday' field.
      * @return The value.
      */
    public java.time.LocalDate getBday() {
      return bday;
    }


    /**
      * Sets the value of the 'bday' field.
      * @param value The value of 'bday'.
      * @return This builder.
      */
    public com.example.flink.avro.Customer.Builder setBday(java.time.LocalDate value) {
      validate(fields()[5], value);
      this.bday = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'bday' field has been set.
      * @return True if the 'bday' field has been set, false otherwise.
      */
    public boolean hasBday() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'bday' field.
      * @return This builder.
      */
    public com.example.flink.avro.Customer.Builder clearBday() {
      bday = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'address' field.
      * @return The value.
      */
    public java.lang.String getAddress() {
      return address;
    }


    /**
      * Sets the value of the 'address' field.
      * @param value The value of 'address'.
      * @return This builder.
      */
    public com.example.flink.avro.Customer.Builder setAddress(java.lang.String value) {
      validate(fields()[6], value);
      this.address = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'address' field has been set.
      * @return True if the 'address' field has been set, false otherwise.
      */
    public boolean hasAddress() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'address' field.
      * @return This builder.
      */
    public com.example.flink.avro.Customer.Builder clearAddress() {
      address = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'email' field.
      * @return The value.
      */
    public java.lang.String getEmail() {
      return email;
    }


    /**
      * Sets the value of the 'email' field.
      * @param value The value of 'email'.
      * @return This builder.
      */
    public com.example.flink.avro.Customer.Builder setEmail(java.lang.String value) {
      validate(fields()[7], value);
      this.email = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'email' field has been set.
      * @return True if the 'email' field has been set, false otherwise.
      */
    public boolean hasEmail() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'email' field.
      * @return This builder.
      */
    public com.example.flink.avro.Customer.Builder clearEmail() {
      email = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'phone' field.
      * @return The value.
      */
    public java.lang.String getPhone() {
      return phone;
    }


    /**
      * Sets the value of the 'phone' field.
      * @param value The value of 'phone'.
      * @return This builder.
      */
    public com.example.flink.avro.Customer.Builder setPhone(java.lang.String value) {
      validate(fields()[8], value);
      this.phone = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'phone' field has been set.
      * @return True if the 'phone' field has been set, false otherwise.
      */
    public boolean hasPhone() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'phone' field.
      * @return This builder.
      */
    public com.example.flink.avro.Customer.Builder clearPhone() {
      phone = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'create_at' field.
      * @return The value.
      */
    public java.time.Instant getCreateAt() {
      return create_at;
    }


    /**
      * Sets the value of the 'create_at' field.
      * @param value The value of 'create_at'.
      * @return This builder.
      */
    public com.example.flink.avro.Customer.Builder setCreateAt(java.time.Instant value) {
      validate(fields()[9], value);
      this.create_at = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'create_at' field has been set.
      * @return True if the 'create_at' field has been set, false otherwise.
      */
    public boolean hasCreateAt() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'create_at' field.
      * @return This builder.
      */
    public com.example.flink.avro.Customer.Builder clearCreateAt() {
      create_at = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'update_at' field.
      * @return The value.
      */
    public java.time.Instant getUpdateAt() {
      return update_at;
    }


    /**
      * Sets the value of the 'update_at' field.
      * @param value The value of 'update_at'.
      * @return This builder.
      */
    public com.example.flink.avro.Customer.Builder setUpdateAt(java.time.Instant value) {
      validate(fields()[10], value);
      this.update_at = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'update_at' field has been set.
      * @return True if the 'update_at' field has been set, false otherwise.
      */
    public boolean hasUpdateAt() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'update_at' field.
      * @return This builder.
      */
    public com.example.flink.avro.Customer.Builder clearUpdateAt() {
      update_at = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'status' field.
      * @return The value.
      */
    public java.lang.String getStatus() {
      return status;
    }


    /**
      * Sets the value of the 'status' field.
      * @param value The value of 'status'.
      * @return This builder.
      */
    public com.example.flink.avro.Customer.Builder setStatus(java.lang.String value) {
      validate(fields()[11], value);
      this.status = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'status' field has been set.
      * @return True if the 'status' field has been set, false otherwise.
      */
    public boolean hasStatus() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'status' field.
      * @return This builder.
      */
    public com.example.flink.avro.Customer.Builder clearStatus() {
      status = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    /**
      * Gets the value of the 'role' field.
      * @return The value.
      */
    public java.lang.String getRole() {
      return role;
    }


    /**
      * Sets the value of the 'role' field.
      * @param value The value of 'role'.
      * @return This builder.
      */
    public com.example.flink.avro.Customer.Builder setRole(java.lang.String value) {
      validate(fields()[12], value);
      this.role = value;
      fieldSetFlags()[12] = true;
      return this;
    }

    /**
      * Checks whether the 'role' field has been set.
      * @return True if the 'role' field has been set, false otherwise.
      */
    public boolean hasRole() {
      return fieldSetFlags()[12];
    }


    /**
      * Clears the value of the 'role' field.
      * @return This builder.
      */
    public com.example.flink.avro.Customer.Builder clearRole() {
      role = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Customer build() {
      try {
        Customer record = new Customer();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Long) defaultValue(fields()[0]);
        record.username = fieldSetFlags()[1] ? this.username : (java.lang.String) defaultValue(fields()[1]);
        record.password = fieldSetFlags()[2] ? this.password : (java.lang.String) defaultValue(fields()[2]);
        record.fname = fieldSetFlags()[3] ? this.fname : (java.lang.String) defaultValue(fields()[3]);
        record.lname = fieldSetFlags()[4] ? this.lname : (java.lang.String) defaultValue(fields()[4]);
        record.bday = fieldSetFlags()[5] ? this.bday : (java.time.LocalDate) defaultValue(fields()[5]);
        record.address = fieldSetFlags()[6] ? this.address : (java.lang.String) defaultValue(fields()[6]);
        record.email = fieldSetFlags()[7] ? this.email : (java.lang.String) defaultValue(fields()[7]);
        record.phone = fieldSetFlags()[8] ? this.phone : (java.lang.String) defaultValue(fields()[8]);
        record.create_at = fieldSetFlags()[9] ? this.create_at : (java.time.Instant) defaultValue(fields()[9]);
        record.update_at = fieldSetFlags()[10] ? this.update_at : (java.time.Instant) defaultValue(fields()[10]);
        record.status = fieldSetFlags()[11] ? this.status : (java.lang.String) defaultValue(fields()[11]);
        record.role = fieldSetFlags()[12] ? this.role : (java.lang.String) defaultValue(fields()[12]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Customer>
    WRITER$ = (org.apache.avro.io.DatumWriter<Customer>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Customer>
    READER$ = (org.apache.avro.io.DatumReader<Customer>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










